import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { StrictMode } from 'react'
import { createMemoryRouter,RouterProvider } from 'react-router-dom'
import { afterEach,describe,expect,it,vi } from 'vitest'
import { AppProviders } from '../../app/providers'
import { appRoutes } from '../../app/router'
const article={id:'a1',title:'RBI liquidity framework',summary:'RBI announced a grounded policy update.',source_title:'RBI',publisher:'RBI',source_url:'https://rbi.org.in/source',source_type:'official',publication_date:'2025-07-04',retrieved_at:'2025-07-04T12:00:00Z',subject:'Economy',topic:'Banking',syllabus_tags_json:[],importance_level:'high',relevance_prelims:'Know the institution.',relevance_mains:'Assess policy effects.',status:'active',created_at:'',updated_at:'',saved:false,opened:false}
const issue={issue_id:'i1',title:article.title,summary:article.summary,subject:'Economy',topic:'Banking',importance_level:'high',publication_date:'2025-07-04',prelims:'Know the institution.',mains:'Assess policy effects.',saved:false,opened:false,score:.9,reasons:['matches Economy focus'],source_tier:'primary',sources:[{article_id:'a1',publisher:'RBI',url:article.source_url,tier:'primary'}]}
function setup(strict=false){const calls:string[]=[];vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=new URL(String(input)),method=init?.method??'GET';calls.push(`${method} ${url.pathname}`);if(url.pathname==='/health')return new Response('{}');if(url.pathname==='/current-affairs/articles')return new Response(JSON.stringify([article]));if(url.pathname==='/current-affairs/personalized')return new Response(JSON.stringify({effective_language:'english',effective_depth:'standard',effective_format:'structured',exam_mode:'prelims',daily_target_minutes:60,issues:[issue],top_stories:[issue],prelims_facts:[],mains_analysis:[],editorials:[],monthly_revision:[],saved_stories:[],revision_due:0,recommended_videos:[]}));if(url.pathname==='/current-affairs/daily')return new Response(JSON.stringify({id:'d1',brief_date:'2025-07-04',language:'english',title:'Daily brief',overview:'One accepted issue.',article_ids_json:['a1'],subject_breakdown_json:{},prelims_points_json:['Institutional fact'],mains_points_json:[],created_at:'',updated_at:''}));if(url.pathname==='/current-affairs/retention/overview')return new Response(JSON.stringify({average_retention:.5,high_risk_articles:[],due_for_revision:[],weak_subjects:[],weekly_trend:[],saved_but_unrevised_article_ids:[]}));if(url.pathname==='/current-affairs/articles/a1/save')return new Response(null,{status:204});return new Response('[]')});const router=createMemoryRouter(appRoutes,{initialEntries:['/current-affairs']});const tree=<AppProviders><RouterProvider router={router}/></AppProviders>;render(strict?<StrictMode>{tree}</StrictMode>:tree);return{calls,router}}
afterEach(()=>{cleanup();vi.restoreAllMocks()})
describe('Current Affairs',()=>{it('renders the latest accepted date, brief, grouped source and no quiz workspace',async()=>{setup();expect(await screen.findByText('RBI liquidity framework')).toBeInTheDocument();expect(screen.getByText(/July 4, 2025/)).toBeInTheDocument();expect(screen.getByText('Daily brief')).toBeInTheDocument();expect(screen.getByRole('link',{name:/Primary source: RBI/})).toHaveAttribute('href',article.source_url);expect(screen.queryByText(/Question 1 of/)).not.toBeInTheDocument()});it('filters and sends one save under Strict Mode',async()=>{const{calls}=setup(true);await screen.findByText('RBI liquidity framework');fireEvent.change(screen.getByPlaceholderText('Search accepted stories'),{target:{value:'missing'}});expect(screen.getByText('No matching stories')).toBeInTheDocument();fireEvent.change(screen.getByPlaceholderText('Search accepted stories'),{target:{value:''}});fireEvent.click(screen.getAllByRole('button',{name:'Save story'})[0]);await waitFor(()=>expect(calls.filter(call=>call==='POST /current-affairs/articles/a1/save')).toHaveLength(1))});it('navigates to the separate quiz page',async()=>{const{router}=setup();await screen.findByText('Daily brief');fireEvent.click(screen.getByRole('link',{name:'Open Quizzes'}));await waitFor(()=>expect(router.state.location.pathname).toBe('/quizzes'))})})
