import { ArrowDown, ArrowRight, BookOpen, Brain, Clock3, FileText, Newspaper, RefreshCw, ShieldAlert, Sparkles, Target, Video } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { EmptyState } from '../../components/feedback/EmptyState'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingSkeleton } from '../../components/feedback/LoadingSkeleton'
import type { MentorAction, PersonalizedIssue, TopicMastery } from '../../api/types'
import { clampPercent, formatDuration, relativeTime, weeklyStudy } from './dashboardUtils'
import { useDashboardData } from './useDashboardData'

const greeting=()=>{const hour=new Date().getHours();return hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'}
const actionRoute=(action:MentorAction)=>action.action_type==='watch_video'?'/videos':action.action_type==='take_quiz'?'/quizzes':action.action_type==='practise_mains_answer'?'/coach':'/revision'
export function DashboardPage(){const data=useDashboardData();const navigate=useNavigate();if(data.criticalPending)return <DashboardSkeleton/>;if(data.criticalError)return <section className="page"><ErrorState title="Dashboard unavailable" message="Your mentor data could not be loaded. Check the local backend and try again." onRetry={()=>void data.refresh()}/></section>
 const mentor=data.mentor.data!,today=data.today.data!,mastery=data.mastery.data!,primary=mentor.recommendations.primary;const targetSeconds=(data.profile.data?.daily_study_target_minutes??mentor.profile.daily_target_minutes)*60;const target=clampPercent(targetSeconds?today.total_study_seconds/targetSeconds*100:0);const story=data.currentAffairs.data?.top_stories[0];const days=weeklyStudy(data.activity.data??[]);const maxDay=Math.max(1,...days.map(day=>day.seconds));
 const act=(operation:'accept'|'complete'|'skip')=>{if(!primary||data.mentorAction.isPending)return;data.mentorAction.mutate({id:primary.id,operation},{onSuccess:()=>{if(operation==='accept')navigate(actionRoute(primary))}})};
 return <section className="dashboard-page"><div className="dashboard-top"><div><span className="eyebrow">PERSONALIZED DAILY PLAN</span><h2>{greeting()}. Your mentor is ready.</h2><p>{mentor.mentor_brief.summary}</p></div><button className="refresh-button" onClick={()=>void data.refresh()} disabled={data.isRefreshing} aria-live="polite"><RefreshCw className={data.isRefreshing?'spin':''}/>{data.isRefreshing?'Refreshing…':'Refresh'}</button></div>
 <div className="hero-grid"><article className="mentor-hero"><div className="hero-label"><Sparkles/> TODAY'S MENTOR PRIORITY</div>{primary?<><h3>{primary.title}</h3><p className="topic-line">{primary.subject} · {primary.topic}</p><p>{primary.reason.join(' ')}</p><div className="hero-meta"><span className={`risk ${primary.priority_level}`}>{primary.priority_level} priority</span><span><Clock3/>{primary.estimated_minutes} min</span></div><div className="hero-actions"><button onClick={()=>act('accept')} disabled={data.mentorAction.isPending}>Start</button><button onClick={()=>act('complete')} disabled={data.mentorAction.isPending}>Complete</button><button onClick={()=>act('skip')} disabled={data.mentorAction.isPending}>Skip</button></div></>:<EmptyState title="No urgent mentor action" message="Continue with your planned study session or review your progress."/>}<span className="action-feedback" aria-live="polite">{data.mentorAction.isSuccess?'Mentor action updated.':data.mentorAction.isError?'The mentor action could not be updated.':''}</span></article>
 <CurrentAffairsPreview story={story} pending={data.currentAffairs.isPending} error={data.currentAffairs.isError} saving={data.saveStory.isPending} onSave={()=>story&&data.saveStory.mutate({id:story.issue_id,saved:story.saved})}/></div>
 <div className="metrics" aria-label="Today’s study metrics"><Metric icon={Clock3} label="Study time today" value={formatDuration(today.total_study_seconds)}/><Metric icon={Target} label="Daily target" value={`${Math.round(target)}%`} detail={`${formatDuration(today.total_study_seconds)} of ${formatDuration(targetSeconds)}`}/><Metric icon={Brain} label="Average mastery" value={`${Math.round(clampPercent(mastery.average_mastery*100))}%`}/><Metric icon={ShieldAlert} label="High-risk topics" value={String(mastery.high_risk_topics.length)}/></div>
 <a className="scroll-cue" href="#dashboard-details">Scroll for more <ArrowDown/></a>
 <div id="dashboard-details" className="dashboard-details"><Card title="Weekly study progress" link="/progress">{data.weekly.isError||data.activity.isError?<SectionError/>:<><div className="week-chart" aria-label={`Seven-day study total ${formatDuration(data.weekly.data?.total_study_seconds??0)}`}>{days.map(day=><div key={day.key}><span style={{height:`${Math.max(4,day.seconds/maxDay*100)}%`}}/><small>{day.label}</small></div>)}</div><p className="card-summary">Total {formatDuration(data.weekly.data?.total_study_seconds??0)} · Daily average {formatDuration((data.weekly.data?.total_study_seconds??0)/7)}</p></>}</Card>
 <Card title="Mastery by subject" link="/progress">{mastery.subject_breakdown.length?<div className="subject-list">{mastery.subject_breakdown.slice(0,5).map(item=><div key={item.subject}><span>{item.subject}</span><progress max="100" value={clampPercent(item.mastery_score*100)}/><strong>{Math.round(clampPercent(item.mastery_score*100))}%</strong></div>)}</div>:<EmptyState title="No mastery evidence" message="Complete quizzes or recall activities to build topic mastery."/>}</Card>
 <TopicCard title="Revision due" topics={mastery.due_for_revision} empty="No urgent revisions are due."/><TopicCard title="Weak and high-risk topics" topics={[...mastery.high_risk_topics,...mastery.weak_topics].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i)} empty="No weak or high-risk topics are available."/>
 <Card title="Current Affairs revision" link="/current-affairs">{data.retention.isError?<SectionError/>:data.retention.data?.due_for_revision.length?<p>{data.retention.data.due_for_revision.length} accepted article{data.retention.data.due_for_revision.length===1?' is':'s are'} due for revision.</p>:<EmptyState title="No Current Affairs revision due" message="Reading or saving articles does not change mastery."/>}</Card>
 <Card title="Recently uploaded PDFs" link="/library">{data.documents.isError?<SectionError/>:data.documents.data?.length?<div className="compact-list">{[...data.documents.data].sort((a,b)=>b.uploaded_at.localeCompare(a.uploaded_at)).slice(0,3).map(doc=><div key={doc.document_id}><FileText/><span><strong>{doc.name}</strong><small>{new Date(doc.uploaded_at).toLocaleDateString()} · {doc.page_count??'—'} pages · {doc.status}</small></span></div>)}</div>:<EmptyState title="No PDFs yet" message="Upload a PDF in My Library to begin grounded learning."/>}</Card>
 <Card title="Recent roadmaps" link="/visual-learning">{data.roadmaps.isError?<SectionError/>:data.roadmaps.data?.length?<div className="compact-list">{data.roadmaps.data.slice(0,3).map(map=><div key={map.id}><BookOpen/><span><strong>{map.title}</strong><small>{map.topic} · {map.visual_type.replace('_',' ')} · {new Date(map.created_at).toLocaleDateString()}</small></span></div>)}</div>:<EmptyState title="No roadmaps yet" message="Generate a roadmap from Visual Learning."/>}</Card>
 <Card title="Trusted videos" link="/videos">{data.videos.isError?<SectionError/>:data.videos.data?.length?<div className="compact-list">{data.videos.data.slice(0,3).map(({video,reasons})=><div key={video.id}><Video/><span><strong>{video.title}</strong><small>{video.source_name} · {formatDuration(video.duration_seconds)} · {reasons[0]}</small></span></div>)}</div>:<EmptyState title="No videos" message="No verified video recommendations are available."/>}</Card>
 <Card title="Recent activity">{data.activity.isError?<SectionError/>:data.activity.data?.filter(event=>!event.event_type.includes('community')).length?<div className="activity-list">{data.activity.data.filter(event=>!event.event_type.includes('community')).slice(0,6).map(event=><div key={event.id}><span>{event.event_type.replaceAll('_',' ')}</span><small>{[event.subject,event.topic].filter(Boolean).join(' · ')||'Study activity'} · {relativeTime(event.occurred_at)}</small></div>)}</div>:<EmptyState title="No recent activity" message="Your recent learning actions will appear here."/>}</Card></div></section>}
function Metric({icon:Icon,label,value,detail}:{icon:typeof Clock3;label:string;value:string;detail?:string}){return <article className="metric-card"><Icon/><div><small>{label}</small><strong>{value}</strong>{detail&&<span>{detail}</span>}</div></article>}
function Card({title,link,children}:{title:string;link?:string;children:React.ReactNode}){return <article className="dashboard-card"><header><h3>{title}</h3>{link&&<Link to={link} aria-label={`Open ${title}`}>View <ArrowRight/></Link>}</header>{children}</article>}
function TopicCard({title,topics,empty}:{title:string;topics:TopicMastery[];empty:string}){return <Card title={title} link="/revision">{topics.length?<div className="topic-list">{topics.slice(0,4).map(topic=><div key={topic.id}><span><strong>{topic.topic}</strong><small>{topic.subject} · {topic.explanation[0]??'Based on current mastery evidence'}</small></span><span className={`risk ${topic.risk_level}`}>{topic.risk_level}</span></div>)}</div>:<EmptyState title="Nothing urgent" message={empty}/>}</Card>}
function CurrentAffairsPreview({story,pending,error,saving,onSave}:{story:PersonalizedIssue|undefined;pending:boolean;error:boolean;saving:boolean;onSave:()=>void}){return <article className="current-preview"><div className="hero-label"><Newspaper/> CURRENT AFFAIRS</div>{pending?<LoadingSkeleton lines={5}/>:error?<SectionError/>:story?<><div className="story-meta"><span className={`risk ${story.importance_level}`}>{story.importance_level}</span><span>{story.publication_date?new Date(`${story.publication_date}T00:00:00`).toLocaleDateString():'Date unavailable'}</span></div><h3>{story.title}</h3><p>{story.summary}</p><small>{story.sources[0]?.publisher??'Approved source'} · {story.subject} · {story.topic}</small><p className="reason">{story.reasons[0]}</p><div className="hero-actions"><Link to="/current-affairs">Open Current Affairs</Link><button onClick={onSave} disabled={saving}>{story.saved?'Unsave':'Save'}</button></div></>:<EmptyState title="No accepted Current Affairs story" message="No accepted Current Affairs content is available yet."/>}</article>}
function SectionError(){return <ErrorState title="Section unavailable" message="This optional information could not be loaded."/>}
function DashboardSkeleton(){return <section className="dashboard-page"><LoadingSkeleton lines={3}/><div className="hero-grid"><LoadingSkeleton lines={7}/><LoadingSkeleton lines={7}/></div><div className="metrics">{[1,2,3,4].map(item=><LoadingSkeleton key={item} lines={3}/>)}</div><div className="dashboard-details">{[1,2,3,4].map(item=><LoadingSkeleton key={item} lines={5}/>)}</div></section>}
