import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { createMemoryRouter, RouterProvider } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { AppProviders } from '../../app/providers'
import { appRoutes } from '../../app/router'

const action={id:'action-1',subject:'Polity',topic:'Fundamental Rights',action_type:'revise_topic',title:'Revise Fundamental Rights',reason:['Forgetting risk is high.'],priority_score:90,priority_level:'urgent',estimated_minutes:20,status:'pending',source_mastery_id:'m1'}
const topic={id:'m1',subject:'Polity',topic:'Fundamental Rights',mastery_score:.42,forgetting_risk:.8,risk_level:'high',confidence_score:.8,total_attempts:3,correct_attempts:1,incorrect_attempts:2,revision_count:0,last_attempt_at:null,last_revised_at:null,next_revision_at:'2026-07-16T00:00:00Z',explanation:['Recent recall failures'],updated_at:'2026-07-16T00:00:00Z'}
const mentor={today:{study_seconds:3600,questions_asked:2,subjects_studied:1,top_subject:'Polity',top_topic:'Fundamental Rights',subject_breakdown:[]},mentor_brief:{summary:'Polity needs focused revision today.',strengths:[],weaknesses:[topic],likely_to_forget:[topic],next_best_action:action},mastery:{average_mastery:.42,strong_topics:[],weak_topics:[topic],high_risk_topics:[topic],subject_breakdown:[{subject:'Polity',mastery_score:.42}]},recommendations:{primary:action,alternatives:[]},recommended_videos:[],profile:{preferred_language:'english',preferred_depth:'standard',preferred_format:'mixed',daily_target_minutes:120},recent_activity:[]}
const summary={total_study_seconds:3600,questions_asked:2,answers_generated:2,pdfs_uploaded:1,subjects_studied:1,top_subject:'Polity',top_topic:'Fundamental Rights',subject_breakdown:[],topic_breakdown:[],recent_events:[]}
const mastery={average_mastery:.42,strong_topics:[],weak_topics:[topic],high_risk_topics:[topic],due_for_revision:[topic],subject_breakdown:[{subject:'Polity',mastery_score:.42}],recent_changes:[topic]}
const story={issue_id:'ca1',title:'RBI updates liquidity framework',summary:'The RBI issued an official policy update.',subject:'Economy',topic:'Monetary Policy',importance_level:'high',publication_date:'2025-07-04',prelims:'Know the institution.',mains:'Assess policy impact.',saved:false,opened:false,score:80,reasons:['Primary official source'],source_tier:'primary',sources:[{article_id:'ca1',publisher:'RBI',url:'https://rbi.org.in/example',tier:'primary'}]}
const payloads:Record<string,unknown>={'/health':{status:'ok',database:'ready',ollama:'reachable',embedding_provider:'ollama',embedding_model:'nomic-embed-text',embedding_model_available:true,embeddings:'available',vector_store:'ready'},'/mentor/dashboard':mentor,'/activity/summary?period=today':summary,'/activity/summary?period=7d':summary,'/mastery/overview':mastery,'/profile':{id:'p1',user_id:'user_001',preferred_language:'english',preferred_depth:'standard',preferred_format:'mixed',daily_study_target_minutes:120,preferred_content_type:'mixed',onboarding_completed:true},'/current-affairs/personalized':{effective_language:'english',effective_depth:'standard',effective_format:'mixed',exam_mode:'prelims',daily_target_minutes:120,issues:[story],top_stories:[story],revision_due:0},'/current-affairs/retention/overview':{average_retention:0,high_risk_articles:[],due_for_revision:[]},'/pdf/documents':[{document_id:'d1',name:'Constitution.pdf',uploaded_at:'2026-07-16T08:00:00Z',status:'indexed',page_count:12,chunk_count:4,embedding_provider:'ollama',embedding_model:'nomic-embed-text',embedding_collection:'documents_ollama_nomic_embed_text',indexed:true}],'/visual-roadmaps':[{id:'r1',status:'ready',title:'Constitution Timeline',subject:'Polity',topic:'Constitution',visual_type:'timeline',language:'english',svg_url:'/visual-roadmaps/r1/svg',created_at:'2026-07-15T00:00:00Z',updated_at:'2026-07-15T00:00:00Z'}],'/videos/recommendations':[{video:{id:'v1',title:'Fundamental Rights Explained',description:'',subject:'Polity',topic:'Fundamental Rights',language:'english',source_name:'Sansad TV',source_url:'https://example.com',thumbnail_url:'',duration_seconds:1200,difficulty:'standard',verified:true,active:true},reasons:['Matches a high-risk topic']}],'/activity/events?limit=100':[{id:'e1',event_type:'study_time_logged',subject:'Polity',topic:'Rights',duration_seconds:3600,metadata:null,occurred_at:new Date().toISOString(),created_at:new Date().toISOString()}]}
function setup(overrides:Record<string,unknown|Response>={}){const calls:string[]=[];vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=new URL(String(input));calls.push(`${init?.method??'GET'} ${url.pathname}${url.search}`);if(url.pathname.startsWith('/mentor/actions/'))return new Response(JSON.stringify(action),{status:200});if(url.pathname==='/current-affairs/articles/ca1/save')return new Response(null,{status:204});const value=overrides[`${url.pathname}${url.search}`]??payloads[`${url.pathname}${url.search}`];return value instanceof Response?value:new Response(JSON.stringify(value),{status:value===undefined?404:200})});const router=createMemoryRouter(appRoutes,{initialEntries:['/dashboard']});render(<AppProviders><RouterProvider router={router}/></AppProviders>);return calls}
afterEach(()=>{cleanup();vi.restoreAllMocks()})
describe('real Dashboard',()=>{
 it('shows a structured loading skeleton',()=>{vi.spyOn(globalThis,'fetch').mockReturnValue(new Promise(()=>{}));const router=createMemoryRouter(appRoutes,{initialEntries:['/dashboard']});render(<AppProviders><RouterProvider router={router}/></AppProviders>);expect(screen.getAllByRole('status',{name:'Loading'}).length).toBeGreaterThan(3)})
 it('renders real mentor, metrics and optional previews',async()=>{setup();expect(await screen.findByText('Revise Fundamental Rights')).toBeInTheDocument();expect(screen.getByText('50%')).toBeInTheDocument();expect(screen.getAllByText('42%').length).toBeGreaterThan(0);expect(screen.getByText('RBI updates liquidity framework')).toBeInTheDocument();expect(screen.getByText('Constitution.pdf')).toBeInTheDocument();expect(screen.getByText('Constitution Timeline')).toBeInTheDocument();expect(screen.getByText('Fundamental Rights Explained')).toBeInTheDocument()})
 it('handles a zero target without NaN or Infinity',async()=>{setup({'/profile':{...payloads['/profile'] as object,daily_study_target_minutes:0}});await screen.findByText('Revise Fundamental Rights');expect(screen.queryByText(/NaN|Infinity/)).not.toBeInTheDocument()})
 it('isolates an optional Current Affairs failure',async()=>{setup({'/current-affairs/personalized':new Response('error',{status:500})});expect(await screen.findByText('Revise Fundamental Rights')).toBeInTheDocument();expect((await screen.findAllByText('Section unavailable',{}, {timeout:3000})).length).toBeGreaterThan(0)})
 it('shows a critical error and retry',async()=>{setup({'/mentor/dashboard':new Response('error',{status:500})});expect(await screen.findByText('Dashboard unavailable',{}, {timeout:3000})).toBeInTheDocument();expect(screen.getByRole('button',{name:/try again/i})).toBeInTheDocument()})
 it('sends one mentor completion request',async()=>{const calls=setup();await screen.findByText('Revise Fundamental Rights');fireEvent.click(screen.getByRole('button',{name:'Complete'}));await waitFor(()=>expect(calls.filter(call=>call==='POST /mentor/actions/action-1/complete')).toHaveLength(1))})
 it('sends one Current Affairs save request',async()=>{const calls=setup();await screen.findByText('RBI updates liquidity framework');fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(calls.filter(call=>call==='POST /current-affairs/articles/ca1/save')).toHaveLength(1))})
})
