import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { CurrentAffairsArticle, CurrentAffairsBrief, CurrentAffairsSummary, PersonalizedCurrentAffairs, getCurrentAffairsArticle, getCurrentAffairsArticles, getCurrentAffairsBriefOptional, getCurrentAffairsSummary, getPersonalizedCurrentAffairs, saveCurrentAffairsArticle } from './api'
import { resolveInitialCurrentAffairsDate } from './currentAffairsDate'
import { SourceBadge } from './ChatPanels'
import type { AppPage } from './AppShell'

const today = () => new Date().toISOString().slice(0, 10)
export function CurrentAffairsPage({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  const [date, setDate] = useState(today()); const [search, setSearch] = useState(''); const [subject, setSubject] = useState(''); const [importance, setImportance] = useState(''); const [savedOnly, setSavedOnly] = useState(false)
  const [articles, setArticles] = useState<CurrentAffairsArticle[]>([]); const [available, setAvailable] = useState<CurrentAffairsArticle[]>([]); const [brief, setBrief] = useState<CurrentAffairsBrief | null>(null); const [summary, setSummary] = useState<CurrentAffairsSummary | null>(null); const [detail, setDetail] = useState<CurrentAffairsArticle | null>(null)
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [briefError, setBriefError] = useState(''); const [dateReady, setDateReady] = useState(false); const manuallySelectedDate = useRef(false)
  const [personalized, setPersonalized] = useState<PersonalizedCurrentAffairs | null>(null)
  async function loadArticles() { setLoading(true); setError(''); const params = new URLSearchParams(); if (date) params.set('date', date); if (search) params.set('search', search); if (subject) params.set('subject', subject); if (importance) params.set('importance', importance); try { setArticles(await getCurrentAffairsArticles(params.toString())) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Current affairs unavailable.') } finally { setLoading(false) } }
  async function loadBrief(force = false) { setBriefError(''); try { setBrief(await getCurrentAffairsBriefOptional(date, force)) } catch (reason) { setBriefError(reason instanceof Error ? reason.message : 'Daily brief unavailable.') } }
  async function refresh(event?: FormEvent) { event?.preventDefault(); const catalog = await getCurrentAffairsArticles(); setAvailable(catalog); await Promise.all([loadArticles(), loadBrief(true), getCurrentAffairsSummary().then(setSummary).catch(() => setSummary(null))]) }
  useEffect(() => { let active = true; void Promise.all([getCurrentAffairsArticles(), getCurrentAffairsSummary().catch(() => null)]).then(([catalog, overview]) => { if (!active) return; setAvailable(catalog); setSummary(overview); setDate(current => resolveInitialCurrentAffairsDate(catalog, today(), current, manuallySelectedDate.current)); setDateReady(true) }).catch(reason => { if (active) { setError(reason instanceof Error ? reason.message : 'Current affairs unavailable.'); setDateReady(true) } }); return () => { active = false } }, [])
  useEffect(() => { if (dateReady) void loadArticles() }, [dateReady, date, subject, importance])
  useEffect(() => { if (dateReady) void loadBrief() }, [dateReady, date])
  useEffect(() => { if (dateReady) void getPersonalizedCurrentAffairs(date).then(setPersonalized).catch(() => setPersonalized(null)) }, [dateReady, date])
  const subjects = useMemo(() => [...new Set(available.map(item => item.subject))], [available])
  const visible = useMemo(() => savedOnly ? articles.filter(item => item.saved) : articles, [articles, savedOnly])
  const ranked = useMemo(() => [...visible].sort((a, b) => ({ high: 3, medium: 2, low: 1 }[b.importance_level] - { high: 3, medium: 2, low: 1 }[a.importance_level])), [visible])
  const topStory = ranked[0]; const headlines = ranked.slice(1, 6); const older = ranked.slice(6)
  async function toggleSave(item: CurrentAffairsArticle) { await saveCurrentAffairsArticle(item.id, item.saved); const update = (rows: CurrentAffairsArticle[]) => rows.map(row => row.id === item.id ? { ...row, saved: !row.saved } : row); setArticles(update); setAvailable(update); window.dispatchEvent(new Event('mentor-data-changed')) }
  async function read(item: CurrentAffairsArticle) { try { setDetail(await getCurrentAffairsArticle(item.id)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Article details unavailable.') } }
  return <div className="current-affairs-page phase-four-page"><header className="phase-page-head"><div><p className="eyebrow">Trusted daily intelligence</p><h1>Current Affairs</h1><small>Grounded UPSC coverage from accepted sources.</small></div><button className="icon-button" onClick={() => void refresh()}>Refresh</button></header>
    <form className="ca-toolbar premium-toolbar" onSubmit={refresh}><label>Date<input type="date" value={date} onChange={e => { manuallySelectedDate.current = true; setDate(e.target.value) }} /></label><label className="grow">Search<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search trusted stories" /></label><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}><option value="">All subjects</option>{subjects.map(value => <option key={value}>{value}</option>)}</select></label><label>Importance<select value={importance} onChange={e => setImportance(e.target.value)}><option value="">All levels</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label className="saved-toggle"><input type="checkbox" checked={savedOnly} onChange={e => setSavedOnly(e.target.checked)} /> Saved</label><button className="send-button">Apply</button></form>
    {loading && <section className="visual-state">Loading accepted Current Affairs…</section>}{error && <section className="visual-state error"><strong>Current Affairs unavailable</strong><p>{error}</p><button onClick={() => void refresh()}>Retry</button></section>}
    {!loading && !error && <><div className="ca-above-fold"><section className="ca-brief premium-card">{briefError ? <><p className="eyebrow">Daily Brief</p><h2>Brief unavailable</h2><p>{briefError}</p><button onClick={() => void loadBrief(true)}>Retry</button></> : brief ? <><div className="card-kicker"><span>Daily Brief</span><time>{brief.brief_date}</time></div><h2>{brief.title}</h2><p>{brief.overview}</p><div className="ca-brief-grid"><article><h3>Prelims facts</h3>{brief.prelims_points_json.slice(0, 3).map(point => <p key={point}>{point}</p>)}</article><article><h3>Mains themes</h3>{brief.mains_points_json.slice(0, 3).map(point => <p key={point}>{point}</p>)}</article></div><footer><span>{brief.article_ids_json.length} accepted sources</span><button onClick={() => document.getElementById('ca-stories')?.scrollIntoView({ behavior: 'smooth' })}>Read brief</button></footer></> : <><p className="eyebrow">Daily Brief</p><h2>No daily brief for {date}</h2><p>Accepted stories remain available. Refresh after a brief has been generated.</p><button onClick={() => void loadBrief(true)}>Refresh brief</button></>}</section>
      {topStory ? <article className="ca-top-story premium-card"><div className="card-kicker"><SourceBadge source={{ source_type: 'current_affairs' }} /><span className={`ca-importance ${topStory.importance_level}`}>{topStory.importance_level}</span></div><p className="source-line">{topStory.publisher} · {topStory.subject} / {topStory.topic}</p><h2>{topStory.title}</h2><p className="top-summary">{topStory.summary}</p><div className="relevance-pair"><div><strong>Prelims</strong><p>{topStory.relevance_prelims}</p></div><div><strong>Mains</strong><p>{topStory.relevance_mains}</p></div></div><div className="roadmap-actions"><a href={topStory.source_url} target="_blank" rel="noopener noreferrer">Open source</a><button onClick={() => void toggleSave(topStory)}>{topStory.saved ? 'Saved' : 'Save story'}</button><button onClick={() => void read(topStory)}>Details</button></div></article> : <section className="visual-state ca-top-story"><strong>No accepted articles</strong><p>Collection has not produced accepted content for this date.</p><button onClick={() => void refresh()}>Refresh collection</button></section>}
      <section className="ca-headlines premium-card"><div className="card-kicker"><span>Top Headlines</span><span>{visible.length} stories</span></div>{headlines.length ? headlines.map(item => <button key={item.id} onClick={() => void read(item)}><span><strong>{item.title}</strong><small>{item.publisher} · {item.subject} · {item.publication_date || new Date(item.retrieved_at).toLocaleDateString()}</small></span><i className={`ca-importance ${item.importance_level}`}>{item.importance_level}</i></button>) : <p>No additional headlines for this date.</p>}</section>
      <section className="ca-quiz-slot premium-card"><p className="eyebrow">Active recall is separate</p><h2>Practice in Quizzes</h2><p>Daily and weekly practice now lives in the dedicated Quizzes workspace.</p><button className="send-button" onClick={() => onNavigate('quizzes')}>Open Quizzes</button></section></div>
      <button className="scroll-more" onClick={() => document.getElementById('ca-retention')?.scrollIntoView({ behavior: 'smooth' })}>Scroll for retention, saved stories and revision ↓</button>
      <section id="ca-stories" className="ca-older premium-card"><div className="card-kicker"><span>More accepted stories</span><span>{summary?.saved_articles ?? 0} saved</span></div>{older.length ? <div className="ca-cards">{older.map(item => <article className="ca-card" key={item.id}><span className={`ca-importance ${item.importance_level}`}>{item.importance_level}</span><h3>{item.title}</h3><p>{item.summary}</p><small>{item.publisher} · {item.subject}</small><div className="roadmap-actions"><button onClick={() => void read(item)}>Read</button><button onClick={() => void toggleSave(item)}>{item.saved ? 'Saved' : 'Save'}</button></div></article>)}</div> : <p>All stories for this date are shown above.</p>}</section>
      {personalized && <div id="ca-retention" className="ca-personalized-grid"><section className="premium-card"><h2>Personalized daily brief</h2><p>{personalized.exam_mode} · {personalized.effective_language} · {personalized.effective_depth} · {personalized.effective_format}</p><p>{personalized.issues.length} duplicate-grouped issues ranked for your study evidence.</p></section><section className="premium-card"><h2>Prelims facts</h2>{personalized.prelims_facts.slice(0, 4).map(item => <article key={item.issue_id}><strong>{item.title}</strong><p>{item.prelims}</p></article>)}</section><section className="premium-card"><h2>Mains analysis</h2>{personalized.mains_analysis.slice(0, 4).map(item => <article key={item.issue_id}><strong>{item.title}</strong><p>{item.mains}</p></article>)}</section><section className="premium-card"><h2>Editorials</h2>{personalized.editorials.length ? personalized.editorials.map(item => <p key={item.issue_id}>{item.title}</p>) : <p>No accepted editorial analysis for this date.</p>}</section><section className="premium-card"><h2>Monthly revision</h2>{personalized.monthly_revision.length ? personalized.monthly_revision.map(item => <p key={item.issue_id}>{item.title}</p>) : <p>No accepted monthly module yet.</p>}</section><section className="premium-card"><h2>Recommended videos</h2>{personalized.recommended_videos.map(item => <p key={item.publisher}><a href={item.url} target="_blank" rel="noreferrer">{item.publisher}</a> · {item.reason}</p>)}</section><section className="premium-card"><h2>Saved stories</h2><p>{personalized.saved_stories.length} grouped issue(s) saved.</p></section><section className="premium-card"><h2>Revision due</h2><p>{personalized.revision_due} Current Affairs item(s) due.</p></section></div>}
    </>}
    {detail && <div className="ca-modal" role="dialog" aria-modal="true"><article><button className="icon-button" onClick={() => setDetail(null)}>Close</button><SourceBadge source={{ source_type: 'current_affairs' }} /><p className="eyebrow">{detail.publisher}</p><h2>{detail.title}</h2><p>{detail.summary}</p><h3>Prelims relevance</h3><p>{detail.relevance_prelims}</p><h3>Mains relevance</h3><p>{detail.relevance_mains}</p><a href={detail.source_url} target="_blank" rel="noopener noreferrer">Open safe source</a></article></div>}
  </div>
}
