import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { CurrentAffairsArticle, CurrentAffairsBrief, getCurrentAffairsArticle, getCurrentAffairsArticles, getCurrentAffairsBriefOptional, saveCurrentAffairsArticle } from './api'
import { CurrentAffairsQuizPanel } from './CurrentAffairsQuizPanel'
import { resolveInitialCurrentAffairsDate } from './currentAffairsDate'

const today = () => new Date().toISOString().slice(0, 10)
export function CurrentAffairsPage() {
  const [date, setDate] = useState(today()); const [search, setSearch] = useState(''); const [subject, setSubject] = useState(''); const [importance, setImportance] = useState('')
  const [articles, setArticles] = useState<CurrentAffairsArticle[]>([]); const [brief, setBrief] = useState<CurrentAffairsBrief | null>(null); const [detail, setDetail] = useState<CurrentAffairsArticle | null>(null)
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [updated, setUpdated] = useState<Date | null>(null)
  const [briefError, setBriefError] = useState('')
  const [copied, setCopied] = useState(false)
  const [dateReady, setDateReady] = useState(false)
  const [availableArticles, setAvailableArticles] = useState<CurrentAffairsArticle[]>([])
  const manuallySelectedDate = useRef(false)
  async function loadArticles() { setLoading(true); setError(''); const params = new URLSearchParams(); if (date) params.set('date', date); if (search) params.set('search', search); if (subject) params.set('subject', subject); if (importance) params.set('importance', importance)
    try { setArticles(await getCurrentAffairsArticles(params.toString())); setUpdated(new Date()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Current affairs unavailable.') } finally { setLoading(false) } }
  async function loadBrief(force = false) { setBriefError(''); try { setBrief(await getCurrentAffairsBriefOptional(date, force)) } catch (reason) { setBriefError(reason instanceof Error ? reason.message : 'Daily brief unavailable.') } }
  async function refresh(event?: FormEvent) { event?.preventDefault(); const catalog = await getCurrentAffairsArticles(); setAvailableArticles(catalog); await Promise.all([loadArticles(), loadBrief(true)]) }
  useEffect(() => { let active = true; void getCurrentAffairsArticles().then(catalog => { if (!active) return; setAvailableArticles(catalog); setDate(current => resolveInitialCurrentAffairsDate(catalog, today(), current, manuallySelectedDate.current)); setDateReady(true) }).catch(reason => { if (active) { setError(reason instanceof Error ? reason.message : 'Current affairs unavailable.'); setDateReady(true) } }); return () => { active = false } }, [])
  useEffect(() => { if (dateReady) void loadArticles() }, [dateReady, date, subject, importance])
  useEffect(() => { if (dateReady) void loadBrief() }, [dateReady, date])
  const subjects = useMemo(() => [...new Set(articles.map(item => item.subject))], [articles])
  const grouped = useMemo(() => articles.reduce<Record<string, CurrentAffairsArticle[]>>((result, item) => { (result[item.subject] ||= []).push(item); return result }, {}), [articles])
  async function toggleSave(item: CurrentAffairsArticle) { await saveCurrentAffairsArticle(item.id, item.saved); setArticles(current => current.map(row => row.id === item.id ? { ...row, saved: !row.saved } : row)); window.dispatchEvent(new Event('mentor-data-changed')) }
  async function read(item: CurrentAffairsArticle) { try { setDetail(await getCurrentAffairsArticle(item.id)); setArticles(current => current.map(row => row.id === item.id ? { ...row, opened: true } : row)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Article details unavailable.') } }
  return <div className="current-affairs-page"><header className="topbar"><div><p className="eyebrow">Trusted daily collection</p><h1>Current Affairs</h1><small>UPSC-focused summaries from approved sources only.</small></div><button className="icon-button" onClick={() => void refresh()}>Refresh</button></header>
    {!loading && !error && <CurrentAffairsQuizPanel selectedDate={date} acceptedArticles={availableArticles} />}
    <form className="ca-toolbar" onSubmit={refresh}><label>Date<input type="date" value={date} onChange={e => { manuallySelectedDate.current = true; setDate(e.target.value) }} /></label><label>Search<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search stories" /></label><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}><option value="">All subjects</option>{subjects.map(value => <option key={value}>{value}</option>)}</select></label><label>Importance<select value={importance} onChange={e => setImportance(e.target.value)}><option value="">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><button className="send-button">Apply</button></form>
    {loading && <section className="visual-state">Loading trusted current affairs…</section>}{error && <section className="visual-state error">{error}<button className="icon-button" onClick={() => void refresh()}>Retry</button></section>}
    {!loading && !error && <div className="ca-content">{briefError ? <section className="visual-state error"><strong>Daily brief could not be loaded</strong><p>{briefError}</p><button className="icon-button" onClick={() => void loadBrief(true)}>Retry</button></section> : brief ? <section className="ca-brief"><p className="eyebrow">Daily Brief</p><h2>{brief.title}</h2><p>{brief.overview}</p><div className="ca-brief-grid"><article><h3>Prelims Facts</h3>{brief.prelims_points_json.map(point => <p key={point}>{point}</p>)}</article><article><h3>Mains Themes</h3>{brief.mains_points_json.map(point => <p key={point}>{point}</p>)}</article></div></section> : <section className="visual-state"><strong>No brief available for this date.</strong><p>Accepted articles remain available below.</p><button className="icon-button" onClick={() => void loadBrief(true)}>Refresh</button></section>}
      {!articles.length ? <section className="visual-state"><strong>No accepted stories</strong><p>No accepted stories are stored for this date yet. Run the local Current Affairs collection command, then refresh this page.</p><code>{`python scripts/collect_current_affairs.py --date ${date} --generate-brief`}</code><button className="icon-button" onClick={() => void navigator.clipboard.writeText(`python scripts/collect_current_affairs.py --date ${date} --generate-brief`).then(() => setCopied(true))}>{copied ? 'Copied' : 'Copy command'}</button><small>Development-only guidance. The student frontend never receives the admin key.</small></section> : Object.entries(grouped).map(([name, items]) => <section className="ca-subject" key={name}><h2>{name}</h2><div className="ca-cards">{(items || []).map(item => <article key={item.id} className="ca-card"><div><span className={`ca-importance ${item.importance_level}`}>{item.importance_level}</span><small>{item.publisher} · {item.publication_date || new Date(item.retrieved_at).toLocaleDateString()}</small></div><h3>{item.title}</h3><p>{item.summary}</p><small>{item.subject} · {item.topic}</small><details><summary>UPSC relevance</summary><strong>Prelims</strong><p>{item.relevance_prelims}</p><strong>Mains</strong><p>{item.relevance_mains}</p></details><div className="roadmap-actions"><button onClick={() => void toggleSave(item)}>{item.saved ? 'Saved' : 'Save'}</button><button onClick={() => void read(item)}>Read details</button><a href={item.source_url} target="_blank" rel="noopener noreferrer">Official source</a></div></article>)}</div></section>)}
      {updated && <p className="privacy-note">Last updated {updated.toLocaleTimeString()}. Reading or saving current affairs does not change mastery.</p>}</div>}
    {detail && <div className="ca-modal" role="dialog" aria-modal="true"><article><button className="icon-button" onClick={() => setDetail(null)}>Close</button><p className="eyebrow">{detail.publisher}</p><h2>{detail.title}</h2><p>{detail.summary}</p><h3>Prelims relevance</h3><p>{detail.relevance_prelims}</p><h3>Mains relevance</h3><p>{detail.relevance_mains}</p><a href={detail.source_url} target="_blank" rel="noopener noreferrer">Open official source</a></article></div>}
  </div>
}
