import { useCallback, useEffect, useMemo, useState } from 'react'
import type React from 'react'
import { Activity, AlertTriangle, BrainCircuit, CalendarDays, CheckCircle2, Clock3, Flame, ListChecks, Play, RefreshCcw, ShieldAlert, Sparkles, Target, TimerReset, TrendingUp, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { AppPage } from './AppShell'
import { ActivitySummary, CurrentAffairsQuizResult, CurrentAffairsRetentionOverview, MasteryOverview, TopicMastery, getActivitySummary, getCurrentAffairsQuizAttempts, getCurrentAffairsQuizzes, getCurrentAffairsRetentionOverview, getMasteryOverview, listMasteryTopics, recordMasteryEvidence } from './api'
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from './PhaseTwoUI'
import { RiskDonutChart, StudyTrendChart, SubjectDonutChart, extractDailyTrend, formatStudyDuration, formatStudyHours } from './StudyCharts'

const pct = (value: number) => Math.round(value * 100)
const dateLabel = (value: string | null) => value ? new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short' }) : 'No revision yet'
const riskLabel = (topic: TopicMastery) => topic.forgetting_risk >= .9 ? 'Critical' : topic.risk_level[0].toUpperCase() + topic.risk_level.slice(1)

function DayProgressCalendar({ dates, title }: { dates: string[]; title: string }) {
  const today = new Date(); const year = today.getFullYear(); const month = today.getMonth()
  const first = new Date(year, month, 1).getDay(); const total = new Date(year, month + 1, 0).getDate()
  const counts = dates.reduce<Record<string, number>>((map, value) => { const date = new Date(value); if (!Number.isNaN(date.getTime()) && date.getFullYear() === year && date.getMonth() === month) map[String(date.getDate())] = (map[String(date.getDate())] || 0) + 1; return map }, {})
  return <section className="phase3-card day-calendar" aria-label={`${title}, ${today.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}`}><header><div><h2>{title}</h2><p>{today.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</p></div><CalendarDays /></header><div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-days">{Array.from({ length: first }, (_, index) => <span key={`blank-${index}`} />)}{Array.from({ length: total }, (_, index) => { const day = index + 1; const count = counts[String(day)] || 0; return <span key={day} className={`${day === today.getDate() ? 'today' : ''} ${count ? 'has-progress' : ''}`} aria-label={`${day}: ${count} recorded ${count === 1 ? 'item' : 'items'}`}><b>{day}</b>{count > 0 && <i>{count}</i>}</span> })}</div><footer><span><i /> Recorded activity</span><span className="calendar-empty-note">Blank days have no recorded data</span></footer></section>
}

export function RevisionCenterPage({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  const [overview, setOverview] = useState<MasteryOverview | null>(null); const [topics, setTopics] = useState<TopicMastery[]>([])
  const [active, setActive] = useState<TopicMastery | null>(null); const [confidence, setConfidence] = useState(3)
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [o, t] = await Promise.all([getMasteryOverview(), listMasteryTopics()]); setOverview(o); setTopics(t) } catch (e) { setError(e instanceof Error ? e.message : 'Revision data is unavailable.') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const due = useMemo(() => overview?.due_for_revision ?? topics.filter(item => item.next_revision_at && new Date(item.next_revision_at) <= new Date()), [overview, topics])
  const risk = useMemo(() => topics.slice().sort((a, b) => b.forgetting_risk - a.forgetting_risk), [topics])
  const estimated = due.reduce((sum, item) => sum + (item.risk_level === 'high' ? 15 : 10), 0)
  async function complete(success: boolean) { if (!active || saving) return; setSaving(true); try { await recordMasteryEvidence({ subject: active.subject, topic: active.topic, evidence_type: success ? 'recall_success' : 'recall_failure', score: success ? confidence / 5 : 0, confidence: confidence / 5, source: 'revision_center' }); setActive(null); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Revision evidence could not be saved.') } finally { setSaving(false) } }
  if (loading) return <div className="phase3-page"><LoadingState label="Building your revision plan…" /></div>
  return <div className="phase3-page revision-center">
    <PageHeader eyebrow="Smart revision" title="Revision Center" subtitle="Prioritise real forgetting risk and strengthen recall with evidence-backed sessions." actions={<span className="phase3-date"><CalendarDays size={15} />{new Date().toLocaleDateString(undefined, { dateStyle: 'medium' })}</span>} />
    {error && <ErrorState description={error} retry={() => void load()} />}
    <section className="revision-hero phase3-card"><div className="phase3-icon violet"><TimerReset /></div><div><span>Today's revision plan</span><h2>{due.length ? `${due.length} topics need attention` : 'You are caught up'}</h2><p>{due.length ? 'Ordered by forgetting risk, mastery and scheduled revision date.' : 'Continue studying to build your revision schedule.'}</p></div><dl><div><dt>Items</dt><dd>{due.length}</dd></div><div><dt>Estimated</dt><dd>{estimated || 0} min</dd></div><div><dt>High risk</dt><dd>{risk.filter(item => item.risk_level === 'high').length}</dd></div></dl><button className="p2-primary" disabled={!due.length} onClick={() => setActive(due[0])}><Play size={15} /> Start Revision</button></section>
    <div className="revision-grid"><section className="phase3-card revision-plan"><header><div><h2>Due for revision</h2><p>Why each topic is in your plan.</p></div><StatusBadge tone={due.length ? 'amber' : 'green'}>{due.length} due</StatusBadge></header>{due.length ? due.map(item => <article key={item.id}><div className={`phase3-icon risk-${item.risk_level}`}><BrainCircuit /></div><div><span>{item.subject}</span><h3>{item.topic}</h3><p>{item.explanation?.[0] || `${riskLabel(item)} forgetting risk based on recorded mastery evidence.`}</p><small>Last revised {dateLabel(item.last_revised_at)} · {item.risk_level === 'high' ? 15 : 10} min</small></div><div className="revision-score"><strong>{pct(item.mastery_score)}%</strong><span>mastery</span><em>{riskLabel(item)} risk</em></div><div className="revision-actions"><button onClick={() => setActive(item)}>Revise now</button><button onClick={() => onNavigate('tests')}>Start test</button></div></article>) : <EmptyState title="No revision items are due today" description="Continue studying to build your revision schedule." />}</section>
      <section className="phase3-card risk-list"><header><div><h2>High-risk topics</h2><p>Topics most likely to be forgotten.</p></div></header>{risk.length ? risk.slice(0, 6).map(item => <article key={item.id}><div><strong>{item.topic}</strong><small>{item.subject} · Last revision {dateLabel(item.last_revised_at)}</small></div><span aria-label={`${riskLabel(item)} risk`}>{riskLabel(item)}</span><div className="phase3-bar"><i style={{ width: `${Math.max(4, pct(1 - item.forgetting_risk))}%` }} /></div><em>{pct(1 - item.forgetting_risk)}% recall</em></article>) : <EmptyState title="No risk evidence yet" description="Complete quizzes and revision sessions to calculate forgetting risk." />}</section></div>
    <div className="revision-analytics"><section className="phase3-card mastery-risk"><header><h2>Mastery vs forgetting risk</h2></header><div className="ring" style={{ '--value': `${pct(overview?.average_mastery ?? 0)}%` } as React.CSSProperties}><strong>{pct(overview?.average_mastery ?? 0)}%</strong><span>overall mastery</span></div><div className="risk-summary"><p><span>Well mastered</span><strong>{overview?.strong_topics.length ?? 0}</strong></p><p><span>At risk</span><strong>{overview?.high_risk_topics.length ?? 0}</strong></p><p><span>Due now</span><strong>{due.length}</strong></p></div></section><RiskDonutChart topics={topics} /><section className="phase3-card subject-load"><header><h2>Subject revision load</h2></header>{Object.entries(due.reduce<Record<string, number>>((acc, item) => { acc[item.subject] = (acc[item.subject] || 0) + 1; return acc }, {})).map(([subject, count]) => <div key={subject}><span>{subject}</span><div className="phase3-bar"><i style={{ width: `${Math.max(8, count / Math.max(due.length, 1) * 100)}%` }} /></div><strong>{count}</strong></div>)}{!due.length && <p className="phase3-muted">No subject load scheduled.</p>}</section></div>
    {active && <div className="phase3-dialog-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="revision-session-title" className="revision-session"><button aria-label="Close revision session" className="dialog-close" onClick={() => setActive(null)}><X /></button><span>{active.subject}</span><h2 id="revision-session-title">{active.topic}</h2><p>{active.explanation?.join(' ') || 'Recall the key ideas without looking at notes, then rate your confidence.'}</p><div className="active-recall"><h3>Active recall</h3><p>Explain the topic aloud or on paper. Identify the core concept, one example and one UPSC application.</p></div><label>How confident was your recall?<input type="range" min="1" max="5" value={confidence} onChange={event => setConfidence(Number(event.target.value))} /><span>{confidence}/5</span></label><div><button onClick={() => void complete(false)} disabled={saving}>Needs work</button><button className="p2-primary" onClick={() => void complete(true)} disabled={saving}><CheckCircle2 /> {saving ? 'Saving…' : 'Recall complete'}</button></div></section></div>}
    <DayProgressCalendar title="Revision calendar" dates={topics.flatMap(item => [item.last_revised_at, item.next_revision_at].filter((value): value is string => Boolean(value)))} />
  </div>
}

export function ProgressAnalyticsPage() {
  const [range, setRange] = useState<'today' | '7d'>('7d'); const [summary, setSummary] = useState<ActivitySummary | null>(null); const [overview, setOverview] = useState<MasteryOverview | null>(null); const [topics, setTopics] = useState<TopicMastery[]>([]); const [retention, setRetention] = useState<CurrentAffairsRetentionOverview | null>(null); const [attempts, setAttempts] = useState<CurrentAffairsQuizResult[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [a, m, t, r, quizzes] = await Promise.all([getActivitySummary(range), getMasteryOverview(), listMasteryTopics(), getCurrentAffairsRetentionOverview().catch(() => null), getCurrentAffairsQuizzes().catch(() => [])]); setSummary(a); setOverview(m); setTopics(t); setRetention(r); setAttempts((await Promise.all(quizzes.map(q => getCurrentAffairsQuizAttempts(q.id).catch(() => [])))).flat()) } catch (e) { setError(e instanceof Error ? e.message : 'Progress analytics are unavailable.') } finally { setLoading(false) } }, [range])
  useEffect(() => { void load() }, [load])
  const trend = useMemo(() => summary ? extractDailyTrend(summary) : [], [summary]); const accuracy = attempts.length ? Math.round(attempts.reduce((s, a) => s + a.percentage, 0) / attempts.length) : null; const strongest = overview?.subject_breakdown.slice().sort((a,b)=>b.mastery_score-a.mastery_score)[0]; const weakest = overview?.subject_breakdown.slice().sort((a,b)=>a.mastery_score-b.mastery_score)[0]; const activeDays = trend.filter(item => item.study_seconds > 0).length; const completed = summary?.recent_events.filter(item => /completed/.test(item.event_type)) ?? []; const mcqs = completed.reduce((sum, item) => sum + Number(item.metadata?.total ?? 0), 0)
  if (loading) return <div className="phase3-page"><LoadingState label="Calculating real progress…" /></div>
  return <div className="phase3-page progress-analytics"><PageHeader eyebrow="Learning analytics" title="Progress Analytics" subtitle="Performance, mastery, retention and consistency calculated from your platform activity." actions={<label className="range-select">Date range<select value={range} onChange={e => setRange(e.target.value as typeof range)}><option value="today">Today</option><option value="7d">Last 7 days</option></select></label>} />{error && <ErrorState description={error} retry={() => void load()} />}
    <section className="progress-metrics">{[[Clock3,'Study time',summary ? formatStudyHours(summary.total_study_seconds) : '—'],[Activity,'Study events',summary?.recent_events.length ?? 0],[Target,'Topics covered',summary?.topic_breakdown.length ?? 0],[ListChecks,'MCQs solved',mcqs],[TrendingUp,'Quiz accuracy',accuracy == null ? 'No attempts' : `${accuracy}%`],[BrainCircuit,'Retention',retention ? `${pct(retention.average_retention)}%` : 'No evidence'],[Flame,'Active days',activeDays],[CheckCircle2,'Completed actions',completed.length]].map(([Icon,label,value]) => { const C = Icon as typeof Clock3; return <article key={String(label)}><div className="phase3-icon"><C /></div><span>{String(label)}</span><strong>{String(value)}</strong></article>})}</section>
    {!summary?.recent_events.length && !topics.length ? <EmptyState title="Not enough activity has been recorded yet" description="Complete study sessions and tests to unlock analytics." /> : <><section className="progress-main-grid"><StudyTrendChart data={trend} /><section className="phase3-card mastery-bars"><header><h2>Subject mastery</h2></header>{overview?.subject_breakdown.length ? overview.subject_breakdown.map(item => <div key={item.subject}><span>{item.subject}</span><div className="phase3-bar"><i style={{ width: `${pct(item.mastery_score)}%` }} /></div><strong>{pct(item.mastery_score)}%</strong></div>) : <p className="phase3-muted">No mastery evidence yet.</p>}</section><RiskDonutChart topics={topics} /></section><section className="progress-secondary-grid"><SubjectDonutChart breakdown={summary?.subject_breakdown ?? []} /><section className="phase3-card accuracy-trend"><header><h2>Quiz accuracy trend</h2></header>{attempts.length ? <ResponsiveContainer width="100%" height={230}><AreaChart data={attempts.map((item,index)=>({name:`Attempt ${index+1}`,accuracy:item.percentage}))}><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false}/><XAxis dataKey="name" tick={{fill:'#8190a8',fontSize:11}}/><YAxis domain={[0,100]} tick={{fill:'#8190a8',fontSize:11}}/><Tooltip/><Area dataKey="accuracy" stroke="#8b5cf6" fill="rgba(124,92,246,.2)"/></AreaChart></ResponsiveContainer> : <EmptyState title="No completed tests yet" description="Start your first test to build performance analytics." />}</section><section className="phase3-card smart-insights"><header><h2><Sparkles /> Smart insights</h2></header><article><ShieldAlert /><div><span>Needs attention</span><strong>{weakest ? `${weakest.subject} · ${pct(weakest.mastery_score)}% mastery` : 'More evidence needed'}</strong></div></article><article><Target /><div><span>Strongest subject</span><strong>{strongest ? `${strongest.subject} · ${pct(strongest.mastery_score)}% mastery` : 'More evidence needed'}</strong></div></article><article><RefreshCcw /><div><span>Next action</span><strong>{topics.sort((a,b)=>b.forgetting_risk-a.forgetting_risk)[0]?.topic || 'Complete a focused study session'}</strong></div></article></section></section></>}
    <DayProgressCalendar title="Day-wise study progression" dates={(summary?.daily_breakdown ?? []).filter(day => day.event_count > 0).map(day => day.date)} />
  </div>
}
