import { useEffect, useState } from 'react'
import { dismissVideo, getVideoRecommendations, openVideo, VideoRecommendation } from './api'

const duration = (seconds: number) => `${Math.ceil(seconds / 60)} min`

export function VideoRecommendations({ subject, topic, explicitRequest = false, initial = [] }: {
  subject?: string | null; topic?: string | null; explicitRequest?: boolean; initial?: VideoRecommendation[]
}) {
  const [items, setItems] = useState(initial); const [language, setLanguage] = useState(''); const [minutes, setMinutes] = useState(30)
  const [loading, setLoading] = useState(!initial.length); const [error, setError] = useState(''); const [expanded, setExpanded] = useState<string | null>(null); const [feedback, setFeedback] = useState('')
  useEffect(() => { let active = true; setLoading(true); setError(''); void getVideoRecommendations({ subject, topic, language: language || undefined, maxDurationSeconds: minutes * 60, explicitRequest }).then(rows => { if (active) setItems(rows) }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : 'Videos unavailable.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [subject, topic, language, minutes, explicitRequest])
  async function watch(item: VideoRecommendation) { setError(''); try { const video = await openVideo(item.video.id); const tab = window.open(video.source_url, '_blank', 'noopener,noreferrer'); if (!tab) setError('The trusted link is available, but your browser blocked the new tab.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Video link unavailable.') } }
  async function dismiss(id: string) { try { await dismissVideo(id); setItems(current => current.filter(item => item.video.id !== id)); setFeedback('Hidden for two days.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to dismiss video.') } }
  return <section className="video-recommendations"><header className="video-heading"><div><p className="eyebrow">Trusted learning resources</p><h3>Recommended videos</h3></div><div className="video-filters"><label>Language<select value={language} onChange={event => setLanguage(event.target.value)}><option value="">Any</option><option value="english">English</option><option value="hindi">Hindi</option><option value="punjabi">Punjabi</option></select></label><label>Maximum length<select value={minutes} onChange={event => setMinutes(Number(event.target.value))}><option value={10}>10 min</option><option value={20}>20 min</option><option value={30}>30 min</option><option value={60}>60 min</option></select></label></div></header>
    {loading ? <div className="video-state">Finding verified resources…</div> : error && !items.length ? <div className="video-state error">{error}</div> : !items.length ? <div className="video-state">No trusted match is available for these filters. Try a broader topic or duration.</div> : <div className="video-grid">{items.map(item => <article className="video-card" key={item.video.id}><div className="video-thumbnail" aria-hidden="true">▶</div><div className="video-content"><div className="video-badges"><span>✓ Verified</span><span>{item.video.language}</span><span>{duration(item.video.duration_seconds)}</span><span>{item.video.difficulty}</span></div><h4>{item.video.title}</h4><p>{item.video.source_name} · {item.video.topic}</p><button className="why-button" aria-expanded={expanded === item.video.id} onClick={() => setExpanded(expanded === item.video.id ? null : item.video.id)}>Why this video?</button>{expanded === item.video.id && <ul className="why-details">{item.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>}<div className="video-actions"><button className="send-button" onClick={() => void watch(item)}>Watch</button><button className="icon-button" onClick={() => setFeedback('Saved for later in this session.')}>Save for Later</button><button className="icon-button danger-button" onClick={() => void dismiss(item.video.id)}>Not Useful</button><button className="icon-button" onClick={() => setFeedback('Ask for a quiz in chat after watching.')}>Take Quiz After Watching</button></div></div></article>)}</div>}
    {feedback && <div className="saved-state">{feedback}</div>}{error && items.length > 0 && <div className="video-state error">{error}</div>}<p className="privacy-note">Videos are selected from a curated trusted-source catalog using your topic, learning preferences, available time, and study evidence.</p></section>
}
