import { API_BASE_URL, ApiError } from './client'
import type { ChatRequest, ChatSource, StreamMetadata } from './types'
export interface StreamCallbacks { onToken:(token:string)=>void; onMetadata:(metadata:StreamMetadata)=>void; onSources?:(sources:ChatSource[])=>void }
export async function streamChat(request:ChatRequest,callbacks:StreamCallbacks,signal:AbortSignal){let response:Response;try{response=await fetch(`${API_BASE_URL}/chat/stream`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'text/event-stream'},body:JSON.stringify(request),signal})}catch(error){if(error instanceof DOMException&&error.name==='AbortError')throw error;throw new ApiError(0,'The study service is unavailable. Check that the backend is running.')}
 if(!response.ok)throw new ApiError(response.status,response.status===422?'The question or response settings were not accepted.':response.status===404?'This conversation is no longer available.':'The local AI request failed.')
 if(!response.body)throw new ApiError(0,'The browser could not read the response stream.')
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',doneEvent=false
 const event=(block:string)=>{let name='message';const lines:string[]=[];for(const line of block.split(/\r?\n/)){if(line.startsWith('event:'))name=line.slice(6).trim();if(line.startsWith('data:'))lines.push(line.slice(5).replace(/^ /,''))}if(!lines.length)return;const raw=lines.join('\n');let value:unknown;try{value=JSON.parse(raw)}catch{throw new ApiError(0,'The local AI returned a malformed stream event.')}if(name==='conversation')callbacks.onMetadata(value as StreamMetadata);else if(name==='token'){const token=(value as {text?:unknown}).text;if(typeof token==='string')callbacks.onToken(token)}else if(name==='sources')callbacks.onSources?.(Array.isArray(value)?value as ChatSource[]:(value as {sources?:ChatSource[]}).sources??[]);else if(name==='error')throw new ApiError(0,(value as {detail?:string}).detail||'The local AI stream failed.');else if(name==='done')doneEvent=true}
 try{while(!doneEvent){const chunk=await reader.read();buffer+=decoder.decode(chunk.value??new Uint8Array(),{stream:!chunk.done});const blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()??'';for(const block of blocks)event(block);if(chunk.done)break}if(buffer.trim())event(buffer)}finally{reader.releaseLock()}
}
