export interface HealthResponse { status: string; database: string; ollama: 'reachable' | 'unreachable'; embedding_provider: string; embedding_model: string; embedding_model_available: boolean; embeddings: string; vector_store: string }
export interface ApiProblem { status: number; message: string; detail?: string }
export interface ActivityBreakdown { name: string; study_seconds: number; event_count: number }
export interface ActivityEvent { id: string; event_type: string; subject: string | null; topic: string | null; duration_seconds: number | null; metadata: Record<string, unknown> | null; occurred_at: string; created_at: string }
export interface ActivitySummary { total_study_seconds: number; questions_asked: number; answers_generated: number; pdfs_uploaded: number; subjects_studied: number; top_subject: string | null; top_topic: string | null; subject_breakdown: ActivityBreakdown[]; topic_breakdown: ActivityBreakdown[]; recent_events: ActivityEvent[] }
export interface TopicMastery { id: string; subject: string; topic: string; mastery_score: number; forgetting_risk: number; risk_level: 'low' | 'medium' | 'high'; confidence_score: number; total_attempts: number; correct_attempts: number; incorrect_attempts: number; revision_count: number; last_attempt_at: string | null; last_revised_at: string | null; next_revision_at: string | null; explanation: string[]; updated_at: string }
export interface MasteryOverview { average_mastery: number; strong_topics: TopicMastery[]; weak_topics: TopicMastery[]; high_risk_topics: TopicMastery[]; due_for_revision: TopicMastery[]; subject_breakdown: Array<{ subject: string; mastery_score: number }>; recent_changes: TopicMastery[] }
export interface MentorAction { id: string; subject: string; topic: string; action_type: 'revise_topic'|'take_quiz'|'review_explanation'|'practise_recall'|'practise_mains_answer'|'watch_video'; title: string; reason: string[]; priority_score: number; priority_level: 'low'|'medium'|'high'|'urgent'; estimated_minutes: number; status: string; source_mastery_id: string }
export interface Video { id: string; title: string; description: string; subject: string; topic: string; language: string; source_name: string; source_url: string; thumbnail_url: string; duration_seconds: number; difficulty: string; verified: boolean; active: boolean }
export interface VideoRecommendation { video: Video; reasons: string[] }
export interface MentorDashboard { today: { study_seconds: number; questions_asked: number; subjects_studied: number; top_subject: string|null; top_topic: string|null; subject_breakdown: ActivityBreakdown[] }; mentor_brief: { summary: string; strengths: TopicMastery[]; weaknesses: TopicMastery[]; likely_to_forget: TopicMastery[]; next_best_action: MentorAction|null }; mastery: { average_mastery: number; strong_topics: TopicMastery[]; weak_topics: TopicMastery[]; high_risk_topics: TopicMastery[]; subject_breakdown: Array<{subject:string;mastery_score:number}> }; recommendations: { primary: MentorAction|null; alternatives: MentorAction[] }; recommended_videos: VideoRecommendation[]; profile: { preferred_language:string; preferred_depth:string; preferred_format:string; daily_target_minutes:number }; recent_activity: ActivityEvent[] }
export interface PersonalizedIssue { issue_id:string; title:string; summary:string; subject:string; topic:string; importance_level:'low'|'medium'|'high'; publication_date:string|null; prelims:string; mains:string; saved:boolean; opened:boolean; score:number; reasons:string[]; source_tier:string; sources:Array<{article_id:string;publisher:string;url:string;tier:string}> }
export interface PersonalizedCurrentAffairs { effective_language:string; effective_depth:string; effective_format:string; exam_mode:string; daily_target_minutes:number; issues:PersonalizedIssue[]; top_stories:PersonalizedIssue[]; prelims_facts:PersonalizedIssue[]; mains_analysis:PersonalizedIssue[]; editorials:PersonalizedIssue[]; monthly_revision:PersonalizedIssue[]; saved_stories:PersonalizedIssue[]; revision_due:number; recommended_videos:VideoRecommendation[] }
export interface CurrentAffairsArticle { id:string;title:string;summary:string;source_title:string;publisher:string;source_url:string;source_type:string;publication_date:string|null;retrieved_at:string;subject:string;topic:string;syllabus_tags_json:unknown[];importance_level:'low'|'medium'|'high';relevance_prelims:string;relevance_mains:string;status:'active'|'archived'|'rejected';created_at:string;updated_at:string;saved:boolean;opened:boolean }
export interface DailyBrief { id:string;brief_date:string;language:string;title:string;overview:string;article_ids_json:string[];subject_breakdown_json:Record<string,unknown>;prelims_points_json:string[];mains_points_json:string[];created_at:string;updated_at:string }
export interface CurrentAffairsRetention { id:string;article_id:string;subject:string;topic:string;retention_score:number;correct_attempts:number;incorrect_attempts:number;recall_failures:number;last_attempt_at:string|null;last_revised_at:string|null;next_revision_at:string|null;risk_level:string;created_at:string;updated_at:string }
export interface QuizQuestion { id:string;question_type:string;question:string;options_json:string[];article_id:string;source_url:string;subject:string;topic:string;difficulty:string }
export interface CurrentAffairsQuiz { id:string;title:string;period_type:'daily'|'weekly'|'custom';date_from:string;date_to:string;question_count:number;difficulty:string;status:string;article_ids_json:string[];questions:QuizQuestion[];created_at:string;updated_at:string }
export interface QuizAnswerResult { question_id:string;correct:boolean;submitted_answer:string;correct_answer:string;explanation:string;article_id:string;source_url:string;topic:string }
export interface QuizAttempt { id:string;quiz_id:string;score:number;total:number;percentage:number;results:QuizAnswerResult[];weak_article_ids:string[];weak_topics:string[];completed_at:string }
export interface PdfDocument { document_id:string; name:string; uploaded_at:string; status:string; page_count:number|null; chunk_count:number|null; embedding_provider:string|null; embedding_model:string|null; embedding_collection:string|null; indexed:boolean }
export interface Roadmap { id:string; status:string; title:string; subject:string; topic:string; visual_type:string; language:string; svg_url:string; created_at:string; updated_at:string }
export interface RetentionOverview { average_retention:number; high_risk_articles:CurrentAffairsRetention[]; due_for_revision:CurrentAffairsRetention[];weak_subjects:Array<{subject:string;score:number}>;weekly_trend:Array<{date:string;percentage:number}>;saved_but_unrevised_article_ids:string[] }
export type StudyMode='learn'|'revision'|'prelims'|'mains'|'interview'
export type ChatLanguage='auto'|'english'|'hindi'|'punjabi'
export type ChatDepth='quick'|'standard'|'detailed'
export type ChatFormat='bullets'|'structured'|'explanation'|'mixed'
export interface Conversation { id:string; title:string; created_at:string; updated_at:string }
export interface ConversationMessage { id:number|string; conversation_id:string; role:'user'|'assistant'; content:string; timestamp:string; streaming?:boolean; sources?:ChatSource[]; subject?:string|null; topic?:string|null; effective_language?:string|null; effective_depth?:string|null; effective_format?:string|null }
export interface ChatSource { source_type?:string; title?:string; document?:string; publisher?:string; url?:string; page?:number; page_start?:number; page_end?:number; confidence?:number }
export interface ChatRequest { question:string; mode:StudyMode; conversation_id?:string; language?:ChatLanguage; depth?:ChatDepth; format?:ChatFormat }
export interface StreamMetadata { conversation_id:string; subject?:string; topic?:string; effective_language?:string; effective_depth?:string; effective_format?:string }
