import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { StrictMode } from 'react'
import { createMemoryRouter,RouterProvider } from 'react-router-dom'
import { afterEach,describe,expect,it,vi } from 'vitest'
import { AppProviders } from '../../app/providers'
import { appRoutes } from '../../app/router'
const article={id:'a1',publication_date:'2025-07-04'};const question={id:'q1',question_type:'true_false',question:'True or false: RBI is the central bank.',options_json:['True','False'],article_id:'a1',source_url:'https://rbi.org.in/source',subject:'Economy',topic:'Banking',difficulty:'standard'};const quiz={id:'z1',title:'Daily Current Affairs Quiz',period_type:'daily',date_from:'2025-07-04',date_to:'2025-07-04',question_count:1,difficulty:'standard',status:'ready',article_ids_json:['a1'],questions:[question],created_at:'',updated_at:''}
function setup(strict=false){const calls:string[]=[];vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=new URL(String(input)),method=init?.method??'GET';calls.push(`${method} ${url.pathname}`);if(url.pathname==='/health')return new Response('{}');if(url.pathname==='/current-affairs/articles')return new Response(JSON.stringify([article]));if(url.pathname==='/current-affairs/quizzes'&&method==='GET')return new Response('[]');if(url.pathname==='/current-affairs/quizzes'&&method==='POST')return new Response(JSON.stringify(quiz));if(url.pathname==='/current-affairs/retention/overview')return new Response(JSON.stringify({average_retention:.5,high_risk_articles:[],due_for_revision:[],weak_subjects:[],weekly_trend:[],saved_but_unrevised_article_ids:[]}));if(url.pathname==='/current-affairs/quizzes/z1/attempts')return new Response('[]');if(url.pathname==='/current-affairs/quizzes/z1/submit')return new Response(JSON.stringify({id:'x1',quiz_id:'z1',score:1,total:1,percentage:100,results:[{question_id:'q1',correct:true,submitted_answer:'True',correct_answer:'True',explanation:'From RBI.',article_id:'a1',source_url:question.source_url,topic:'Banking'}],weak_article_ids:[],weak_topics:[],completed_at:''}));return new Response('[]')});const router=createMemoryRouter(appRoutes,{initialEntries:['/quizzes']});const tree=<AppProviders><RouterProvider router={router}/></AppProviders>;render(strict?<StrictMode>{tree}</StrictMode>:tree);return calls}
afterEach(()=>{cleanup();vi.restoreAllMocks()})
describe('Quizzes',()=>{it('creates and submits exactly once under Strict Mode',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);const calls=setup(true);await screen.findByRole('button',{name:'Create quiz'});fireEvent.change(screen.getByLabelText('Questions'),{target:{value:'1'}});fireEvent.click(screen.getByRole('button',{name:'Create quiz'}));expect(await screen.findByText('Question 1 of 1')).toBeInTheDocument();expect(calls.filter(call=>call==='POST /current-affairs/quizzes')).toHaveLength(1);fireEvent.click(screen.getByLabelText('True'));fireEvent.click(screen.getByRole('button',{name:'Submit quiz'}));expect(await screen.findByText('1 of 1 · 100%')).toBeInTheDocument();expect(screen.getByText('From RBI.')).toBeInTheDocument();expect(screen.getByRole('link',{name:/Open accepted source/})).toHaveAttribute('href',question.source_url);expect(calls.filter(call=>call==='POST /current-affairs/quizzes/z1/submit')).toHaveLength(1)});it('validates custom date range before creation',async()=>{const calls=setup();await screen.findByRole('button',{name:'Create quiz'});fireEvent.change(screen.getByLabelText('From'),{target:{value:'2025-07-05'}});fireEvent.click(screen.getByRole('button',{name:'Create quiz'}));expect(screen.getByText('Choose a valid date range and 1–20 questions.')).toBeInTheDocument();expect(calls.filter(call=>call==='POST /current-affairs/quizzes')).toHaveLength(0)})})
