CATALOG = [
    dict(id="vid_polity_rights_en", title="Fundamental Rights and the Constitution", description="Official parliamentary learning material on constitutional rights.", subject="Polity and Governance", topic="Fundamental Rights", language="english", source_name="Sansad TV", source_url="https://www.youtube.com/@SansadTV/videos", thumbnail_url="", duration_seconds=1200, difficulty="standard"),
    dict(id="vid_economy_monetary_en", title="Monetary Policy and the Repo Rate", description="Public education material on monetary policy and central banking.", subject="Economy", topic="Monetary Policy", language="english", source_name="Reserve Bank of India", source_url="https://www.youtube.com/@reservebankofindia/videos", thumbnail_url="", duration_seconds=900, difficulty="standard"),
    dict(id="vid_history_modern_hi", title="Modern India: National Movement", description="Curriculum-aligned history learning material.", subject="History and Art & Culture", topic="Modern History", language="hindi", source_name="NCERT Official", source_url="https://www.youtube.com/@NCERTOFFICIAL/videos", thumbnail_url="", duration_seconds=1500, difficulty="beginner"),
    dict(id="vid_geography_climate_en", title="Indian Monsoon and Climatology", description="Curriculum-aligned geography learning material.", subject="Geography", topic="Climatology", language="english", source_name="NCERT Official", source_url="https://www.youtube.com/@NCERTOFFICIAL/videos", thumbnail_url="", duration_seconds=1100, difficulty="standard"),
    dict(id="vid_environment_bio_en", title="Biodiversity and Conservation", description="Official environmental awareness and conservation material.", subject="Environment and Ecology", topic="Biodiversity", language="english", source_name="Ministry of Environment", source_url="https://www.youtube.com/@moefccgoi/videos", thumbnail_url="", duration_seconds=1000, difficulty="standard"),
    dict(id="vid_science_space_en", title="Indian Space Science and Technology", description="Official science outreach from India's space programme.", subject="Science and Technology", topic="Space Technology", language="english", source_name="ISRO Official", source_url="https://www.youtube.com/@isroofficial5866/videos", thumbnail_url="", duration_seconds=1300, difficulty="standard"),
    dict(id="vid_current_pib_en", title="Government Policy Explainers", description="Official public-information explainers for policy developments.", subject="Current Affairs", topic="Government Policy", language="english", source_name="PIB India", source_url="https://www.youtube.com/@PIBIndia/videos", thumbnail_url="", duration_seconds=600, difficulty="standard"),
]
