import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { createMemoryRouter, RouterProvider } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { AppProviders } from '../../app/providers'
import { appRoutes } from '../../app/router'
const conversations=[{id:'a',title:'Polity A',created_at:'2026-07-16T00:00:00Z',updated_at:'2026-07-16T02:00:00Z'},{id:'b',title:'Economy B',created_at:'2026-07-16T00:00:00Z',updated_at:'2026-07-16T01:00:00Z'}]
const histories:Record<string,unknown>={a:[{id:1,conversation_id:'a',role:'user',content:'A question',timestamp:'2026-07-16T00:00:00Z'},{id:2,conversation_id:'a',role:'assistant',content:'A answer',timestamp:'2026-07-16T00:01:00Z'}],b:[{id:3,conversation_id:'b',role:'user',content:'B question',timestamp:'2026-07-16T00:02:00Z'}]}
function stream(){return new Response(new ReadableStream({start(controller){const enc=new TextEncoder();controller.enqueue(enc.encode('event: conversation\ndata: {"conversation_id":"a","subject":"Polity","topic":"Rights","effective_language":"english","effective_depth":"standard","effective_format":"mixed"}\n\n'));controller.enqueue(enc.encode('event: token\ndata: {"text":"Streamed "}\n\n'));controller.enqueue(enc.encode('event: token\ndata: {"text":"answer"}\n\n'));controller.enqueue(enc.encode('event: done\ndata: {"status":"complete"}\n\n'));controller.close()}}),{status:200})}
function setup(){const calls:string[]=[];vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=new URL(String(input)),method=init?.method??'GET';calls.push(`${method} ${url.pathname}`);if(url.pathname==='/health')return new Response(JSON.stringify({status:'ok',database:'ready',ollama:'reachable',embedding_provider:'ollama',embedding_model:'nomic-embed-text',embedding_model_available:true,embeddings:'available',vector_store:'ready'}));if(url.pathname==='/profile')return new Response(JSON.stringify({id:'p',user_id:'u',preferred_language:'english',preferred_depth:'standard',preferred_format:'mixed',daily_study_target_minutes:120,preferred_content_type:'mixed',onboarding_completed:true}));if(url.pathname==='/conversations'&&method==='GET')return new Response(JSON.stringify(conversations));if(url.pathname==='/conversations'&&method==='POST')return new Response(JSON.stringify({id:'c',title:'New Conversation',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}),{status:201});if(url.pathname.endsWith('/messages'))return new Response(JSON.stringify(histories[url.pathname.split('/')[2]]??[]));if(url.pathname==='/chat/stream')return stream();if(method==='PATCH')return new Response(JSON.stringify({...conversations[0],title:'Renamed'}));if(method==='DELETE')return new Response(null,{status:204});return new Response('{}')});const router=createMemoryRouter(appRoutes,{initialEntries:['/coach']});render(<AppProviders><RouterProvider router={router}/></AppProviders>);return calls}
afterEach(()=>{cleanup();vi.restoreAllMocks()})
describe('AI Study Coach',()=>{
 it('loads real conversations and keeps A/B histories isolated',async()=>{setup();expect(await screen.findByText('A answer')).toBeInTheDocument();fireEvent.click(screen.getByText('Economy B').closest('button')!);expect(await screen.findByText('B question')).toBeInTheDocument();expect(screen.queryByText('A answer')).not.toBeInTheDocument();fireEvent.click(screen.getByText('Polity A').closest('button')!);expect(await screen.findByText('A answer')).toBeInTheDocument();expect(screen.queryByText('B question')).not.toBeInTheDocument()})
 it('sends one stream request and renders one progressive answer',async()=>{const calls=setup();await screen.findByText('A answer');fireEvent.change(screen.getByPlaceholderText('Ask your UPSC mentor…'),{target:{value:'Explain DPSP'}});fireEvent.click(screen.getByRole('button',{name:/send/i}));expect(await screen.findByText('Streamed answer')).toBeInTheDocument();expect(screen.getAllByText('Streamed answer')).toHaveLength(1);expect(calls.filter(call=>call==='POST /chat/stream')).toHaveLength(1);expect(screen.getAllByText('Explain DPSP')).toHaveLength(1)})
 it('Enter sends once while Shift+Enter preserves a newline',async()=>{const calls=setup();await screen.findByText('A answer');const box=screen.getByPlaceholderText('Ask your UPSC mentor…');fireEvent.change(box,{target:{value:'Line one'}});fireEvent.keyDown(box,{key:'Enter',shiftKey:true});expect(calls.filter(call=>call==='POST /chat/stream')).toHaveLength(0);fireEvent.keyDown(box,{key:'Enter'});await waitFor(()=>expect(calls.filter(call=>call==='POST /chat/stream')).toHaveLength(1))})
 it('rename and confirmed delete each send one mutation',async()=>{const calls=setup();await screen.findByText('A answer');vi.spyOn(window,'prompt').mockReturnValue('Renamed');vi.spyOn(window,'confirm').mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Rename Polity A'}));await waitFor(()=>expect(calls.filter(call=>call==='PATCH /conversations/a')).toHaveLength(1));fireEvent.click(screen.getByRole('button',{name:'Delete Renamed'}));await waitFor(()=>expect(calls.filter(call=>call==='DELETE /conversations/a')).toHaveLength(1))})
})
