import { useQueryClient } from '@tanstack/react-query'
import { useEffect, useRef, useState } from 'react'
import { streamChat } from '../../api/chat'
import type { ChatFormat, ChatLanguage, ChatDepth, ConversationMessage, StudyMode, StreamMetadata } from '../../api/types'
import { conversationKeys } from './chatQueryKeys'
export type StreamState='idle'|'preparing'|'retrieving'|'generating'|'completed'|'cancelled'|'failed'
export function useChatStream(){const client=useQueryClient();const guard=useRef(false),controller=useRef<AbortController|null>(null);const [state,setState]=useState<StreamState>('idle'),[elapsed,setElapsed]=useState(0),[error,setError]=useState(''),[metadata,setMetadata]=useState<StreamMetadata|null>(null)
 useEffect(()=>{if(!guard.current)return;const timer=window.setInterval(()=>setElapsed(Math.floor((Date.now()-started.current)/1000)),1000);return()=>clearInterval(timer)},[state]);const started=useRef(0)
 // Mutable refs are the synchronous single-flight and elapsed-time boundary for one active stream.
 // eslint-disable-next-line react-hooks/immutability
 const send=async(conversationId:string,question:string,settings:{mode:StudyMode;language?:ChatLanguage;depth?:ChatDepth;format?:ChatFormat})=>{if(guard.current)return false;guard.current=true;controller.current=new AbortController();started.current=Date.now();setElapsed(0);setError('');setMetadata(null);setState('preparing');const now=new Date().toISOString(),userId=`user-${Date.now()}`,assistantId=`assistant-${Date.now()}`;client.setQueryData<ConversationMessage[]>(conversationKeys.messages(conversationId),old=>[...(old??[]),{id:userId,conversation_id:conversationId,role:'user',content:question,timestamp:now},{id:assistantId,conversation_id:conversationId,role:'assistant',content:'',timestamp:now,streaming:true}]);let received=false
 try{setState('retrieving');await streamChat({question,mode:settings.mode,conversation_id:conversationId,...(settings.language?{language:settings.language}:{}),...(settings.depth?{depth:settings.depth}:{}),...(settings.format?{format:settings.format}:{})},{onMetadata:value=>{setMetadata(value)},onSources:sources=>client.setQueryData<ConversationMessage[]>(conversationKeys.messages(conversationId),old=>(old??[]).map(row=>row.id===assistantId?{...row,sources}:row)),onToken:token=>{received=true;setState('generating');client.setQueryData<ConversationMessage[]>(conversationKeys.messages(conversationId),old=>(old??[]).map(row=>row.id===assistantId?{...row,content:row.content+token}:row))}},controller.current.signal);setState('completed');client.setQueryData<ConversationMessage[]>(conversationKeys.messages(conversationId),old=>(old??[]).map(row=>row.id===assistantId?{...row,streaming:false}:row))}catch(reason){const cancelled=reason instanceof DOMException&&reason.name==='AbortError';setState(cancelled?'cancelled':'failed');setError(cancelled?'Generation stopped. The partial answer has been preserved.':reason instanceof Error?reason.message:'The local AI stream was interrupted.');client.setQueryData<ConversationMessage[]>(conversationKeys.messages(conversationId),old=>(old??[]).map(row=>row.id===assistantId?{...row,streaming:false,content:row.content||(!received?'Reliable supporting material was not found. Upload a relevant PDF or refine your question.':'')}:row))}finally{guard.current=false;controller.current=null}return true}
 const cancel=()=>controller.current?.abort();return{send,cancel,state,elapsed,error,metadata,isStreaming:['preparing','retrieving','generating'].includes(state)}}
